name: LOK CI Debug

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice libc++-dev libc++abi-dev

      - name: Run tests
        run: PDFIUM_STATIC_LIB_PATH=$PWD/libs/x86_64-unknown-linux-gnu cargo test -- --nocapture 2>&1
